
 

/*TABLA PEQUEÑA*/
SELECT * 
INTO DATAMART_INTURSA_HOY
FROM DATAMART_INTURSA
WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<='11/20/2018') OR
		(FLAG_STG='1' AND FECCORTE='11/20/2018' AND FECESTADIAHUESPED>'11/20/2018')
    )


/****FUNCIONES REVENUE*****/
--DROP FUNCTION REVENUE_OTB
CREATE FUNCTION REVENUE_OTB(
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT
AS BEGIN
DECLARE @RR AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE; 

SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  

IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V
	AND DESSEGMENTO=@SEGMENTO_V;
END

ELSE IF(@SEGMENTO_V='ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V;
END

ELSE IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V='ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESSEGMENTO=@SEGMENTO_V;
END
ELSE
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN;

END

IF(@RR > 1000000)
BEGIN
	SET @RR = ROUND(@RR/1000,0)*1000 
END

RETURN(@RR)
        
END
/***********************/


/*********FUNCIONES ROOMNIGHTS*************/
CREATE FUNCTION ROOMNIGHT_OTB(
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT
AS BEGIN
DECLARE @RN AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE; 

SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  

IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RN= SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V
	AND DESSEGMENTO=@SEGMENTO_V;
END

ELSE IF(@SEGMENTO_V='ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RN= SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V;
END

ELSE IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V='ALL')
BEGIN
	SELECT  @RN= SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESSEGMENTO=@SEGMENTO_V;
END
ELSE
BEGIN
	SELECT  @RN= SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN;

END

RETURN(@RN)
        
END

/******************************************/


/*********FUNCIONES ADR********************/
CREATE FUNCTION ADR_OTB(
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT
AS BEGIN
DECLARE @ADR AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE; 

SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  

IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @ADR= SUM(ROOM_REVENUE)/SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V
	AND DESSEGMENTO=@SEGMENTO_V;
END

ELSE IF(@SEGMENTO_V='ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @ADR= SUM(ROOM_REVENUE)/SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V;
END

ELSE IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V='ALL')
BEGIN
	SELECT  @ADR= SUM(ROOM_REVENUE)/SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESSEGMENTO=@SEGMENTO_V;
END
ELSE
BEGIN
	SELECT  @ADR= SUM(ROOM_REVENUE)/SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN;

END

RETURN(@ADR)
        
END
/******************************************/


/*********FUNCIONES OCUPACION********************/
CREATE FUNCTION OCUPACION_OTB(
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT 
AS BEGIN
DECLARE @CAPACIDAD AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE,
		@RN AS FLOAT;

SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  
SET		@RN = DBO.ROOMNIGHT_OTB(@FINICIO_STR,@FFIN_STR,@SEGMENTO_V,@HOTEL_V)

IF(@HOTEL_V<>'ALL')
BEGIN
	SELECT  @CAPACIDAD= SUM(CAPACIDAD)*DATEDIFF(day,@FFIN,@FINICIO)
	FROM HOTEL 
	WHERE DESHOTEL=@HOTEL_V
END

ELSE
BEGIN
	SELECT  @CAPACIDAD= SUM(CAPACIDAD)*DATEDIFF(day,@FFIN,@FINICIO)
	FROM HOTEL

END

RETURN(@RN/@CAPACIDAD)
        
END
/******************************************/





/*****PRUEBA 4*******/
CREATE FUNCTION MAESTRA( @FCORTE_STR NVARCHAR(50),
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT
AS BEGIN
DECLARE @RR AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE; 

SET		@FCORTE = CONVERT(DATE,@FCORTE_STR,103)
SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  

IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V
	AND DESSEGMENTO=@SEGMENTO_V;
END

ELSE IF(@SEGMENTO_V='ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V;
END

ELSE IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V='ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESSEGMENTO=@SEGMENTO_V;
END
ELSE
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN;

END

RETURN(@RR)
        
END
/*********************************/
