SELECT DBO.FMASTER_2('REVENUE','20/11/2018','01/11/2018','30/11/2018','RETAIL','Westin')
SELECT DBO.FMASTER('ADR','01/11/2018','30/11/2018','ALL','Tambo del Inka')
SELECT DBO.ADR_OTB('01/11/2018','30/11/2018','RETAIL','Westin')



SELECT SUM(ROOM_REVENUE) 
FROM DATAMART_INTURSA
WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<='11/20/2018') OR
		(FLAG_STG='1' AND FECCORTE='11/20/2018' AND FECESTADIAHUESPED>'11/20/2018')
    )
AND FECESTADIAHUESPED>='11/30/2018' AND FECESTADIAHUESPED<='11/01/2018'
 

/*TABLA PEQUEÑA*/
SELECT * 
INTO DATAMART_INTURSA_HOY
FROM DATAMART_INTURSA
WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<='11/20/2018') OR
		(FLAG_STG='1' AND FECCORTE='11/20/2018' AND FECESTADIAHUESPED>'11/20/2018')
    )


/*****FUNCION PRINCIPAL*******/
--DROP FUNCTION FMASTER
CREATE FUNCTION FMASTER_2 (	@METRICA NVARCHAR(50),
							@FCORTE_STR NVARCHAR(50),
							@FINICIO_STR NVARCHAR(50),
							@FFIN_STR NVARCHAR(50),
							@SEGMENTO_V NVARCHAR(50),
							@HOTEL_V NVARCHAR(50))
RETURNS FLOAT
AS BEGIN
DECLARE @DATO AS FLOAT
IF(@METRICA = 'ADR')
BEGIN
	SET @DATO = DBO.ADR(@FCORTE_STR,@FINICIO_STR,@FFIN_STR,@SEGMENTO_V,@HOTEL_V) 
END
ELSE IF (@METRICA = 'REVENUE')
BEGIN
	SET @DATO = DBO.REVENUE(@FCORTE_STR,@FINICIO_STR,@FFIN_STR,@SEGMENTO_V,@HOTEL_V) 
END
ELSE IF (@METRICA = 'ROOMNIGHT')
BEGIN
	SET @DATO = DBO.ROOMNIGHT(@FCORTE_STR,@FINICIO_STR,@FFIN_STR,@SEGMENTO_V,@HOTEL_V) 
END
ELSE IF(@METRICA = 'OCUPACION')
BEGIN
	SET @DATO = DBO.OCUPACION(@FCORTE_STR,@FINICIO_STR,@FFIN_STR,@SEGMENTO_V,@HOTEL_V) 
END
ELSE
BEGIN
	SET @DATO = NULL
END
RETURN(@DATO)
END
/*****************************/


/****FUNCIONES REVENUE*****/
--DROP FUNCTION REVENUE
CREATE FUNCTION REVENUE(
						  @FCORTE_STR NVARCHAR(50),
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT
AS BEGIN
DECLARE @RR AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE; 

SET		@FCORTE = CONVERT(DATE,@FCORTE_STR,103)  
SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  

IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V
	AND DESSEGMENTO=@SEGMENTO_V;
END

ELSE IF(@SEGMENTO_V='ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V;
END

ELSE IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V='ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESSEGMENTO=@SEGMENTO_V;
END
ELSE
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN;

END

IF(@RR > 1000000)
BEGIN
	SET @RR = ROUND(@RR/1000,0)*1000 
END
ELSE IF(@RR > 10000)
BEGIN
	SET @RR = ROUND(@RR/1000,0)*1000 
END
ELSE
BEGIN
	SET @RR = ROUND(@RR,0)
END
RETURN(@RR)
        
END
/***********************/


/*********FUNCIONES ROOMNIGHTS*************/
--DROP FUNCTION ROOMNIGHT
CREATE FUNCTION ROOMNIGHT(
						  @FCORTE_STR NVARCHAR(50),
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT
AS BEGIN
DECLARE @RN AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE; 

SET		@FCORTE = CONVERT(DATE,@FCORTE_STR,103)  
SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  

IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RN= SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V
	AND DESSEGMENTO=@SEGMENTO_V;
END

ELSE IF(@SEGMENTO_V='ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RN= SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V;
END

ELSE IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V='ALL')
BEGIN
	SELECT  @RN= SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESSEGMENTO=@SEGMENTO_V;
END
ELSE
BEGIN
	SELECT  @RN= SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN;

END

RETURN(@RN)
        
END

/******************************************/


/*********FUNCIONES ADR********************/
--DROP FUNCTION ADR
CREATE FUNCTION ADR(  @FCORTE_STR NVARCHAR(50),
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT
AS BEGIN
DECLARE @ADR AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE;

SET		@FCORTE = CONVERT(DATE,@FCORTE_STR,103)  		
SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  

IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @ADR= SUM(ROOM_REVENUE)/SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V
	AND DESSEGMENTO=@SEGMENTO_V;
END

ELSE IF(@SEGMENTO_V='ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @ADR= SUM(ROOM_REVENUE)/SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V;
END

ELSE IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V='ALL')
BEGIN
	SELECT  @ADR= SUM(ROOM_REVENUE)/SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESSEGMENTO=@SEGMENTO_V;
END
ELSE
BEGIN
	SELECT  @ADR= SUM(ROOM_REVENUE)/SUM(ROOM_NIGHT)
	FROM DATAMART_INTURSA
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN;

END

RETURN(@ADR)
        
END
/******************************************/


/*********FUNCIONES OCUPACION********************/
CREATE FUNCTION OCUPACION( @FCORTE_STR NVARCHAR(50),
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT 
AS BEGIN
DECLARE @CAPACIDAD AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE,
		@RN AS FLOAT;

SET		@FCORTE = CONVERT(DATE,@FCORTE_STR,103)  
SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  
SET		@RN = DBO.ROOMNIGHT_OTB(@FINICIO_STR,@FFIN_STR,@SEGMENTO_V,@HOTEL_V)

IF(@HOTEL_V<>'ALL')
BEGIN
	SELECT  @CAPACIDAD= SUM(CAPACIDAD)*DATEDIFF(day,@FFIN,@FINICIO)
	FROM HOTEL 
	WHERE DESHOTEL=@HOTEL_V
END

ELSE
BEGIN
	SELECT  @CAPACIDAD= SUM(CAPACIDAD)*DATEDIFF(day,@FFIN,@FINICIO)
	FROM HOTEL

END

RETURN(@RN/@CAPACIDAD)
        
END
/******************************************/





/*****PRUEBA 4*******/
CREATE FUNCTION MAESTRA( @FCORTE_STR NVARCHAR(50),
                          @FINICIO_STR NVARCHAR(50),
                          @FFIN_STR NVARCHAR(50),
                          @SEGMENTO_V NVARCHAR(50),
                          @HOTEL_V NVARCHAR(50))
RETURNS FLOAT
AS BEGIN
DECLARE @RR AS FLOAT,
		@FCORTE AS DATE,
		@FINICIO AS DATE,
		@FFIN AS DATE; 

SET		@FCORTE = CONVERT(DATE,@FCORTE_STR,103)
SET		@FINICIO = CONVERT(DATE,@FINICIO_STR,103)
SET		@FFIN = CONVERT(DATE,@FFIN_STR,103)  

IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V
	AND DESSEGMENTO=@SEGMENTO_V;
END

ELSE IF(@SEGMENTO_V='ALL' AND @HOTEL_V<>'ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESHOTEL=@HOTEL_V;
END

ELSE IF(@SEGMENTO_V<>'ALL' AND @HOTEL_V='ALL')
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN
	AND DESSEGMENTO=@SEGMENTO_V;
END
ELSE
BEGIN
	SELECT  @RR= SUM(ROOM_REVENUE)
	FROM DATAMART_INTURSA_HOY
	WHERE 
    (   (FLAG_STG='0' AND FECESTADIAHUESPED<=@FCORTE) OR
		(FLAG_STG='1' AND FECCORTE=@FCORTE AND FECESTADIAHUESPED>@FCORTE)
    )
	AND FECESTADIAHUESPED>=@FINICIO AND FECESTADIAHUESPED<=@FFIN;

END

RETURN(@RR)
        
END
/*********************************/
